// src/cli/commands/setup.ts
import { Command } from "commander";
import inquirer from "inquirer";
import chalk from "chalk";
import ora from "ora";
import fs from "fs";
import { showLogo, showSuccess, showError } from "../logo.js";
import { CLAUDE_MODELS } from "../../claude/models.js";

export const setupCommand = new Command("setup")
  .description("Interactive setup wizard for NovaClaw")
  .action(async () => {
    showLogo();
    console.log(chalk.yellow("Welcome to NovaClaw Setup\n"));

    try {
      const { botToken } = await inquirer.prompt([
        {
          type: "input",
          name: "botToken",
          message: "Telegram Bot Token (from @BotFather):",
          validate: (input) => input.length > 20 ? true : "Token invalide",
        },
      ]);

      const { ownerId } = await inquirer.prompt([
        {
          type: "input",
          name: "ownerId",
          message: "Ton Telegram User ID (envoie /start à @userinfobot):",
          validate: (input) => /^\d+$/.test(input) ? true : "Doit être un nombre",
        },
      ]);

      const { allowedIds } = await inquirer.prompt([
        {
          type: "input",
          name: "allowedIds",
          message: "Autres User IDs autorisés (séparés par virgule, ou vide):",
          default: "",
        },
      ]);

      const modelChoices = Object.entries(CLAUDE_MODELS).map(([key, model]) => ({
        name: `${model.name} - ${model.description}`,
        value: key,
      }));

      const { claudeModel } = await inquirer.prompt([
        {
          type: "list",
          name: "claudeModel",
          message: "Modèle Claude par défaut:",
          choices: modelChoices,
          default: "sonnet-4.6",
        },
      ]);

      const { language } = await inquirer.prompt([
        {
          type: "list",
          name: "language",
          message: "Langue par défaut:",
          choices: [
            { name: "Français", value: "fr" },
            { name: "English", value: "en" },
          ],
          default: "fr",
        },
      ]);

      const allIds = [ownerId, ...allowedIds.split(",").filter(Boolean)].join(",");

      const spinner = ora("Creating configuration...").start();

      const envContent = `# NovaClaw Configuration
# Generated by novaclaw setup

# Telegram
TELEGRAM_BOT_TOKEN=${botToken}
TELEGRAM_OWNER_ID=${ownerId}
TELEGRAM_ALLOWED_IDS=${allIds}

# Claude (leave empty to use Claude Code auth)
ANTHROPIC_API_KEY=
CLAUDE_MODEL=${CLAUDE_MODELS[claudeModel].id}

# Database
DATABASE_PATH=./data/novaclaw.db

# Language
DEFAULT_LANGUAGE=${language}

# Logging
LOG_LEVEL=info
NODE_ENV=production
`;

      fs.writeFileSync(".env", envContent);
      spinner.succeed("Configuration created");

      const dirs = ["data", "data/workspaces", "logs"];
      for (const dir of dirs) {
        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir, { recursive: true });
        }
      }
      showSuccess("Directories created");

      console.log("\n" + chalk.green("═".repeat(50)));
      console.log(chalk.green.bold("\n✓ NovaClaw configuré avec succès!\n"));
      console.log(chalk.white("Prochaines étapes:"));
      console.log(chalk.gray("  1. Lance l'agent:     ") + chalk.cyan("novaclaw start"));
      console.log(chalk.gray("  2. Envoie /start à ton bot Telegram"));
      console.log(chalk.green("\n" + "═".repeat(50) + "\n"));
    } catch (error) {
      showError(`Setup failed: ${error}`);
      process.exit(1);
    }
  });
